/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package smartcar.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CarOperation implements org.apache.thrift.TEnum {
  FORWARD(1),
  BACK(2),
  LEFT(3),
  RIGHT(4),
  CLOCKWISE(5),
  COUNTERCLOCKWISE(6),
  STOP(7);

  private final int value;

  private CarOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CarOperation findByValue(int value) { 
    switch (value) {
      case 1:
        return FORWARD;
      case 2:
        return BACK;
      case 3:
        return LEFT;
      case 4:
        return RIGHT;
      case 5:
        return CLOCKWISE;
      case 6:
        return COUNTERCLOCKWISE;
      case 7:
        return STOP;
      default:
        return null;
    }
  }
}
