/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package smartcar.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SmartMapThrift implements org.apache.thrift.TBase<SmartMapThrift, SmartMapThrift._Fields>, java.io.Serializable, Cloneable, Comparable<SmartMapThrift> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SmartMapThrift");

  private static final org.apache.thrift.protocol.TField OBEJCT_BIN_FIELD_DESC = new org.apache.thrift.protocol.TField("obejctBin", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SmartMapThriftStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SmartMapThriftTupleSchemeFactory());
  }

  public ByteBuffer obejctBin; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OBEJCT_BIN((short)1, "obejctBin");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OBEJCT_BIN
          return OBEJCT_BIN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OBEJCT_BIN, new org.apache.thrift.meta_data.FieldMetaData("obejctBin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SmartMapThrift.class, metaDataMap);
  }

  public SmartMapThrift() {
  }

  public SmartMapThrift(
    ByteBuffer obejctBin)
  {
    this();
    this.obejctBin = obejctBin;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SmartMapThrift(SmartMapThrift other) {
    if (other.isSetObejctBin()) {
      this.obejctBin = org.apache.thrift.TBaseHelper.copyBinary(other.obejctBin);
;
    }
  }

  public SmartMapThrift deepCopy() {
    return new SmartMapThrift(this);
  }

  @Override
  public void clear() {
    this.obejctBin = null;
  }

  public byte[] getObejctBin() {
    setObejctBin(org.apache.thrift.TBaseHelper.rightSize(obejctBin));
    return obejctBin == null ? null : obejctBin.array();
  }

  public ByteBuffer bufferForObejctBin() {
    return obejctBin;
  }

  public SmartMapThrift setObejctBin(byte[] obejctBin) {
    setObejctBin(obejctBin == null ? (ByteBuffer)null : ByteBuffer.wrap(obejctBin));
    return this;
  }

  public SmartMapThrift setObejctBin(ByteBuffer obejctBin) {
    this.obejctBin = obejctBin;
    return this;
  }

  public void unsetObejctBin() {
    this.obejctBin = null;
  }

  /** Returns true if field obejctBin is set (has been assigned a value) and false otherwise */
  public boolean isSetObejctBin() {
    return this.obejctBin != null;
  }

  public void setObejctBinIsSet(boolean value) {
    if (!value) {
      this.obejctBin = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OBEJCT_BIN:
      if (value == null) {
        unsetObejctBin();
      } else {
        setObejctBin((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OBEJCT_BIN:
      return getObejctBin();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OBEJCT_BIN:
      return isSetObejctBin();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SmartMapThrift)
      return this.equals((SmartMapThrift)that);
    return false;
  }

  public boolean equals(SmartMapThrift that) {
    if (that == null)
      return false;

    boolean this_present_obejctBin = true && this.isSetObejctBin();
    boolean that_present_obejctBin = true && that.isSetObejctBin();
    if (this_present_obejctBin || that_present_obejctBin) {
      if (!(this_present_obejctBin && that_present_obejctBin))
        return false;
      if (!this.obejctBin.equals(that.obejctBin))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SmartMapThrift other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetObejctBin()).compareTo(other.isSetObejctBin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetObejctBin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.obejctBin, other.obejctBin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SmartMapThrift(");
    boolean first = true;

    sb.append("obejctBin:");
    if (this.obejctBin == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.obejctBin, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SmartMapThriftStandardSchemeFactory implements SchemeFactory {
    public SmartMapThriftStandardScheme getScheme() {
      return new SmartMapThriftStandardScheme();
    }
  }

  private static class SmartMapThriftStandardScheme extends StandardScheme<SmartMapThrift> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SmartMapThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OBEJCT_BIN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.obejctBin = iprot.readBinary();
              struct.setObejctBinIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SmartMapThrift struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.obejctBin != null) {
        oprot.writeFieldBegin(OBEJCT_BIN_FIELD_DESC);
        oprot.writeBinary(struct.obejctBin);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SmartMapThriftTupleSchemeFactory implements SchemeFactory {
    public SmartMapThriftTupleScheme getScheme() {
      return new SmartMapThriftTupleScheme();
    }
  }

  private static class SmartMapThriftTupleScheme extends TupleScheme<SmartMapThrift> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SmartMapThrift struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetObejctBin()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetObejctBin()) {
        oprot.writeBinary(struct.obejctBin);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SmartMapThrift struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.obejctBin = iprot.readBinary();
        struct.setObejctBinIsSet(true);
      }
    }
  }

}

